package com.love.origami.model;

import java.util.Date;

public class Paperinnovate extends  PageBean{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_paper_innovate.id
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_paper_innovate.title
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_paper_innovate.type_id
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    private Byte typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_paper_innovate.version_no
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    private Integer versionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_paper_innovate.created_by_id
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    private Long createdById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_paper_innovate.created_time
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_paper_innovate.last_updated_by_id
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    private Long lastUpdatedById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_paper_innovate.last_updated_time
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    private Date lastUpdatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_paper_innovate.deleted_flag
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    private Boolean deletedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_paper_innovate.content
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_paper_innovate.id
     *
     * @return the value of ch_paper_innovate.id
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_paper_innovate.id
     *
     * @param id the value for ch_paper_innovate.id
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_paper_innovate.title
     *
     * @return the value of ch_paper_innovate.title
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_paper_innovate.title
     *
     * @param title the value for ch_paper_innovate.title
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_paper_innovate.type_id
     *
     * @return the value of ch_paper_innovate.type_id
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public Byte getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_paper_innovate.type_id
     *
     * @param typeId the value for ch_paper_innovate.type_id
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public void setTypeId(Byte typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_paper_innovate.version_no
     *
     * @return the value of ch_paper_innovate.version_no
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_paper_innovate.version_no
     *
     * @param versionNo the value for ch_paper_innovate.version_no
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_paper_innovate.created_by_id
     *
     * @return the value of ch_paper_innovate.created_by_id
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public Long getCreatedById() {
        return createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_paper_innovate.created_by_id
     *
     * @param createdById the value for ch_paper_innovate.created_by_id
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public void setCreatedById(Long createdById) {
        this.createdById = createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_paper_innovate.created_time
     *
     * @return the value of ch_paper_innovate.created_time
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_paper_innovate.created_time
     *
     * @param createdTime the value for ch_paper_innovate.created_time
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_paper_innovate.last_updated_by_id
     *
     * @return the value of ch_paper_innovate.last_updated_by_id
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public Long getLastUpdatedById() {
        return lastUpdatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_paper_innovate.last_updated_by_id
     *
     * @param lastUpdatedById the value for ch_paper_innovate.last_updated_by_id
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public void setLastUpdatedById(Long lastUpdatedById) {
        this.lastUpdatedById = lastUpdatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_paper_innovate.last_updated_time
     *
     * @return the value of ch_paper_innovate.last_updated_time
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public Date getLastUpdatedTime() {
        return lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_paper_innovate.last_updated_time
     *
     * @param lastUpdatedTime the value for ch_paper_innovate.last_updated_time
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_paper_innovate.deleted_flag
     *
     * @return the value of ch_paper_innovate.deleted_flag
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public Boolean getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_paper_innovate.deleted_flag
     *
     * @param deletedFlag the value for ch_paper_innovate.deleted_flag
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public void setDeletedFlag(Boolean deletedFlag) {
        this.deletedFlag = deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_paper_innovate.content
     *
     * @return the value of ch_paper_innovate.content
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_paper_innovate.content
     *
     * @param content the value for ch_paper_innovate.content
     *
     * @mbggenerated Fri Aug 26 16:46:15 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }
}