package com.love.origami.dao;


import java.util.List;

import com.love.origami.model.Paperinnovate;

public interface paperinnovateMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ch_paper_innovate
	 * @mbggenerated  Fri Aug 26 16:46:15 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ch_paper_innovate
	 * @mbggenerated  Fri Aug 26 16:46:15 CST 2016
	 */
	int insert(Paperinnovate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ch_paper_innovate
	 * @mbggenerated  Fri Aug 26 16:46:15 CST 2016
	 */
	int insertSelective(Paperinnovate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ch_paper_innovate
	 * @mbggenerated  Fri Aug 26 16:46:15 CST 2016
	 */
	Paperinnovate selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ch_paper_innovate
	 * @mbggenerated  Fri Aug 26 16:46:15 CST 2016
	 */
	int updateByPrimaryKeySelective(Paperinnovate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ch_paper_innovate
	 * @mbggenerated  Fri Aug 26 16:46:15 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(Paperinnovate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ch_paper_innovate
	 * @mbggenerated  Fri Aug 26 16:46:15 CST 2016
	 */
	int updateByPrimaryKey(Paperinnovate record);

	int isDup(Paperinnovate record);
    
    List<Paperinnovate> selectByCondition(Paperinnovate paperinnovate);
    
    int searchCount(Paperinnovate paperinnovate);
    
    Paperinnovate getById(Integer id);
}